### ISSUE TITLE
how to run the rosbag

### ISSUE THREAD

**Issue by jxr041100** [floatlazer/semantic_slam#1]
when i came to your demo, trying to run rosbag. I have download the demo.bag. 
then I start to run the following command:
roslaunch semantic_slam semantic_mapping.launch
it will wait for the incoming data from demo.bag, right?
 so next step, I am playing the 
rosbag play demo.bag. 

Please correct me if I misunderstood here.

**Comment by floatlazer** [comment]
Yes, that's how I run it. Is there anything not working ?

**Comment by floatlazer** [comment]
I will correct the README, the name of the bag was different with the downloaded file.
