### ISSUE TITLE
Cannot save Octomap

### ISSUE THREAD

**Issue by jsdd25** [floatlazer/semantic_slam#16]
Hi!
Your work is amazing! I tried to save the Octomap. However, the binary file which is saved does not contain an OcTree! Could you give me some advice about how to save Octomap?
```
jin@jin-System-Product-Name:~/map$ octovis map.bt 
ERROR: Binary file does not contain an OcTree!
ERROR: First line of OcTree file header does not start with "# Octomap OcTree binary file"
```
Thanks!

**Comment by victor123499** [comment]
@jsdd25 
Are you try to change the type?
You can try to save the map.ot, it have the color type.

**Comment by jsdd25** [comment]
I have saved the color map. Thank you very much!
