### ISSUE TITLE
semantic_cloud.py unable to import from color_pcl_generator

### ISSUE THREAD

**Issue by codieboomboom** [floatlazer/semantic_slam#26]
Hi, anybody know how to solve this?

Traceback (most recent call last):
  File "/home/boom/catkin_ws/src/semantic_slam/semantic_cloud/src/semantic_cloud.py", line 21, in <module>
    from color_pcl_generator import PointType, ColorPclGenerator
  File "/home/boom/catkin_ws/devel/lib/python3/dist-packages/color_pcl_generator/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
ImportError: cannot import name 'PointType' from partially initialized module 'color_pcl_generator' (most likely due to a circular import) (/home/boom/catkin_ws/devel/lib/python3/dist-packages/color_pcl_generator/__init__.py)
[semantic_cloud-2] process has died [pid 6982, exit code 1, cmd /home/boom/catkin_ws/src/semantic_slam/semantic_cloud/src/semantic_cloud.py __name:=semantic_cloud __log:=/home/boom/.ros/log/08006776-e2f5-11ea-a59a-6397d188ae3a/semantic_cloud-2.log].
log file: /home/boom/.ros/log/08006776-e2f5-11ea-a59a-6397d188ae3a/semantic_cloud-2*.log

I'm trying to run this with the demo rosbag and seems to be stuck at this issue.

**Comment by Yueting-Li** [comment]
Hi guy! have you solved this problem?

**Comment by codieboomboom** [comment]
@Yueting-Li which version of Python running? Maybe you can try modifying the __init__.py file in the include folder of color_pcl_generator.py and remove the import statement, seems to help for me

**Comment by Yueting-Li** [comment]
Thanks for your advice! I am running Python 2.7. It seems to help for me, too. No error now.
