### ISSUE TITLE
How to save the otcomap?

### ISSUE THREAD

**Issue by valar-JRJ** [floatlazer/semantic_slam#42]
I run the launch file semantic_mapping.launch successfully but the map didn't get saved. How to save the octomap?

**Comment by codieboomboom** [comment]
It should be automatically saved based on the path provided in the octomap_generator.yaml file. Try changing the path to "/home/your_user_name/map_name.ot" or "/home/your_user_name/map_name.bt"

**Comment by valar-JRJ** [comment]
> It should be automatically saved based on the path provided in the octomap_generator.yaml file. Try changing the path to "/home/your_user_name/map_name.ot" or "/home/your_user_name/map_name.bt"

problem solved, thanks

**Comment by jason866695** [comment]
> It should be automatically saved based on the path provided in the octomap_generator.yaml file. Try changing the path to "/home/your_user_name/map_name.ot" or "/home/your_user_name/map_name.bt"

does that means,after i run the semantic_mapping.launch and finish the map building,and shut down the command windows,then i can find my map with my order path?because i cant find my map,and i dont know why,thanks.
